config_name: AAAConfig
content:
  Bacon:
    __articles:
    - 虽无才能，却有性格.md
    __attribute: &id001
      Index: true
      Visibility: true
    __resouces: []
  Blog:
    __articles:
    - BlogIndex.md
    - 书架-0.md
    - 关于DTO与DO的小思考.md
    - 初识OverlayFS.md
    - 删库跑路.md
    - 第一篇.md
    - 算法刷题小记-0.md
    - 设计、搬砖与糊墙.md
    __attribute: *id001
    __resouces: []
  Life:
    __articles:
    - HowOldAreYou.md
    - LifeIndex.md
    - 冷冷的冰雨.md
    - 加菲猫不过情人节.md
    - 太阳照常升起.md
    - 尤里安想成为杨.md
    - 想吃吐鲁番葡萄.md
    - 想要飞.md
    - 打卡.md
    - 砖家.md
    __attribute: *id001
    __resouces: []
    image:
      __articles: []
      __attribute: *id001
      __resouces:
      - 加菲猫不过情人节_0.jpg
      - 加菲猫不过情人节_1.jpg
      - 尤里安想成为杨_0.jpg
      - 尤里安想成为杨_1.jpg
    music:
      __articles: []
      __attribute: *id001
      __resouces:
      - Surface - Shower Me With Your Love.mp3
      - 久石让-太阳照常升起.mp3
  ReadingNotes:
    __articles:
    - ReadingNotesIndex.md
    - 马恩选集.md
    __attribute: *id001
    __resouces: []
  __articles:
  - index.md
  __attribute: *id001
  __resouces:
  - _config.yml
